### PR TITLE
Allow to iter over section keys

### PR DESCRIPTION
**Pull request by fbochu**

### CODE REVIEW

**Comment by rbarrois** [comment]
What would be the use for this feature?

So far, getconf only reads explicitly defined values, which helps in plugging various additional backends.

**Comment by fbochu** [comment]
In our uwsgi launcher, we allow ops to override some settings but for now this settings are limited by a predefined list. By allowing to iterate over section keys, ops would be allowed to override all uwsgi settings.

Of course we can have an index key to list all keys from the section, but in this case ops should list all keys in the index key even if they have not overridden the value (or maybe a system with two index keys, but listing keys from section seen easier).

@tonio have a similar issue in financial configuration.

**Comment by tonio** [comment]
@fbochu I don’t (-;

**Comment by fbochu** [comment]
Oups, sorry ! I get the wrong nickname...

@tonial  --^

**Comment by rbarrois** [comment]
@fbochu Well, I'm not convinced :) uwsgi has quite a lot of options, of which only a few make sense.

I'm still in favor of the "explicit over implicit" approach!

**Comment by fbochu** [comment]
Looking back, I think this is actually not the right approach to my problem. I will use two special keys to list options in section (one for defaults and one for user defined options).

**Pull request closed without merging**
